export const SITES_REGISTRY = [
    {
        id: "mangoenterprise",
        name: "Mango Enterprise",
        base_url: "https://mangoenterprise.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "mangoenterprise",
    },
    {
        id: "zeewatches",
        name: "Zee Watches",
        base_url: "https://zeewatches.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "zeewatches",
    },
    {
        id: "wristtimess",
        name: "Wrist Timess",
        base_url: "https://wristtimess.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "wristtimess",
    },
    {
        id: "watchhouse11",
        name: "Watch House 11",
        base_url: "https://watchhouse11.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchhouse11",
    },
    {
        id: "watchgalleryin",
        name: "Watch Gallery IN",
        base_url: "https://watchgalleryin.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchgalleryin",
    },
    {
        id: "fashionpro123",
        name: "Fashion Pro 123",
        base_url: "https://fashionpro123.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "fashionpro123",
    },
    {
        id: "maenterprise",
        name: "MA Enterprise",
        base_url: "https://maenterprise.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "maenterprise",
    },
    {
        id: "eye_care",
        name: "Eye Care",
        base_url: "https://eye-care.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "eyecare",
    },
    {
        id: "famwatch",
        name: "Fam Watch",
        base_url: "https://famwatch.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "famwatch",
    },
    {
        id: "watchclub",
        name: "Watch Club",
        base_url: "https://watchclub.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchclub",
    },
    {
        id: "watchcultures",
        name: "Watch Cultures",
        base_url: "https://watchcultures.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchcultures",
    },
    {
        id: "bismiwatches",
        name: "Bismi Watches",
        base_url: "https://bismiwatches.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "bismiwatches",
    },
    {
        id: "awwaltime11",
        name: "Awwal Time 11",
        base_url: "https://awwaltime11.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "awwaltime11",
    },
    {
        id: "wristifyreseller",
        name: "Wristify Reseller",
        base_url: "https://wristifyreseller.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "wristifyreseller",
    },
    {
        id: "watchfactorys",
        name: "Watch Factorys",
        base_url: "https://watchfactorys.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchfactorys",
    },
    {
        id: "watchkart",
        name: "Watch Kart",
        base_url: "https://watchkart.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchkart",
    },
    {
        id: "timepiece",
        name: "Timepiece",
        base_url: "https://timepiece.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "timepiece",
    },
    {
        id: "hypewrist",
        name: "Hype Wrist",
        base_url: "https://hypewrist.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "hypewrist",
    },
    {
        id: "jilaniwatches11",
        name: "Jilani Watches 11",
        base_url: "https://jilaniwatches11.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "jilaniwatches11",
    },
    {
        id: "saenterprise",
        name: "SA Enterprise",
        base_url: "https://saenterprise.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "saenterprise",
    },
    {
        id: "thetimekeepers",
        name: "The Timekeepers",
        base_url: "https://thetimekeepers.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "thetimekeepers",
    },
    {
        id: "watchcode1",
        name: "Watch Code 1",
        base_url: "https://watchcode1.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchcode1",
    },
    {
        id: "uzer_watch",
        name: "Uzer Watch",
        base_url: "https://uzer-watch.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "uzerwatch",
    },
    {
        id: "utstorewatch",
        name: "UT Store Watch",
        base_url: "https://utstorewatch.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "utstorewatch",
    },
    {
        id: "watch_aqua",
        name: "Watch Aqua",
        base_url: "https://watch-aqua.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchaqua",
    },
    {
        id: "watch_adda",
        name: "Watch Adda",
        base_url: "https://watch-adda.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchadda",
    },
    {
        id: "spwatches",
        name: "SP Watches",
        base_url: "https://spwatches.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "spwatches",
    },
    {
        id: "watch_enterprise17",
        name: "Watch Enterprise 17",
        base_url: "https://watch-enterprise17.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchenterprise17",
    },
    {
        id: "watchstore17",
        name: "Watch Store 17",
        base_url: "https://watchstore17.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchstore17",
    },
    {
        id: "city_watch19",
        name: "City Watch 19",
        base_url: "https://city-watch19.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "citywatch19",
    },
    {
        id: "timezone17",
        name: "Timezone 17",
        base_url: "https://timezone17.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "timezone17",
    },
    {
        id: "watchflex",
        name: "Watch Flex",
        base_url: "https://watchflex.cartpe.in/",
        category: "watches",
        method: "METHOD_A",
        searchKey: "watchflex",
    },
];
