export const SITES_REGISTRY = [
  // ================= WATCH SITES =================
  // { id: "ticktock", name: "ticktock", base_url: "https://ticktock.jdwebnship.com/", category: "watches", method: "METHOD_B", searchKey: "ticktock" },
  // { id: "kdenterprise", name: "kdenterprise", base_url: "https://kdenterprise.jdwebnship.com/", category: "watches", method: "METHOD_B", searchKey: "kdenterprise" },
  // { id: "watchflex", name: "watchflex", base_url: "https://watchflex.jdwebnship.com/", category: "watches", method: "METHOD_B", searchKey: "watchflex" },
  // { id: "watchstreet", name: "watch-street", base_url: "https://watch-street.jdwebnship.com/", category: "watches", method: "METHOD_B", searchKey: "watchstreet" },
  // { id: "timepieceJD", name: "timepieceJD", base_url: "https://timepiece.jdwebnship.com/", category: "watches", method: "METHOD_B", searchKey: "timepieceJD" },
  // { id: "mangoenterprise", name: "Mango Enterprise", base_url: "https://mangoenterprise.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "mangoenterprise" },
  // { id: "zeewatches", name: "Zee Watches", base_url: "https://zeewatches.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "zeewatches" },
  // { id: "wristtimess", name: "Wrist Timess", base_url: "https://wristtimess.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "wristtimess" },
  // { id: "watchhouse11", name: "Watch House 11", base_url: "https://watchhouse11.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchhouse11" },
  // { id: "watchgalleryin", name: "Watch Gallery In", base_url: "https://watchgalleryin.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchgalleryin" },
  // { id: "fashionpro123", name: "Fashion Pro 123", base_url: "https://fashionpro123.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "fashionpro123" },
  // { id: "maenterprise", name: "MA Enterprise", base_url: "https://maenterprise.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "maenterprise" },
  // { id: "eye-care", name: "Eye Care", base_url: "https://eye-care.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "eye-care" },
  // { id: "famwatch", name: "Fam Watch", base_url: "https://famwatch.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "famwatch" },
  // { id: "watchclub", name: "Watch Club", base_url: "https://watchclub.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchclub" },
  // { id: "watchcultures", name: "Watch Cultures", base_url: "https://watchcultures.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchcultures" },
  // { id: "bismiwatches", name: "Bismi Watches", base_url: "https://bismiwatches.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "bismiwatches" },
  // { id: "awwaltime11", name: "Awwal Time 11", base_url: "https://awwaltime11.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "awwaltime11" },
  // { id: "wristifyreseller", name: "Wristify Reseller", base_url: "https://wristifyreseller.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "wristifyreseller" },
  // { id: "watchfactorys", name: "Watch Factorys", base_url: "https://watchfactorys.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchfactorys" },
  // { id: "watchkart", name: "Watch Kart", base_url: "https://watchkart.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchkart" },
  // { id: "timepiece", name: "Timepiece", base_url: "https://timepiece.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "timepiece" },
  // { id: "hypewrist", name: "Hype Wrist", base_url: "https://hypewrist.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "hypewrist" },
  // { id: "jilaniwatches11", name: "Jilani Watches 11", base_url: "https://jilaniwatches11.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "jilaniwatches11" },
  // { id: "saenterprise", name: "SA Enterprise", base_url: "https://saenterprise.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "saenterprise" },
  // { id: "thetimekeepers", name: "The Timekeepers", base_url: "https://thetimekeepers.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "thetimekeepers" },
  // { id: "watchcode1", name: "Watch Code 1", base_url: "https://watchcode1.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchcode1" },
  // { id: "uzerwatch", name: "Uzer Watch", base_url: "https://uzerwatch.cartpe.in", category: "watches", method: "METHOD_A", searchKey: "uzerwatch" },
  // { id: "utstorewatch", name: "UT Store Watch", base_url: "https://utstorewatch.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "utstorewatch" },
  // { id: "watch-aqua", name: "Watch Aqua", base_url: "https://watch-aqua.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watch-aqua" },
  // { id: "watch-adda", name: "Watch Adda", base_url: "https://watch-adda.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watch-adda" },
  // { id: "spwatches", name: "SP Watches", base_url: "https://spwatches.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "spwatches" },
  // { id: "watch-enterprise17", name: "Watch Enterprise 17", base_url: "https://watch-enterprise17.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watch-enterprise17" },
  // { id: "watchstore17", name: "Watch Store 17", base_url: "https://watchstore17.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchstore17" },
  // { id: "city-watch19", name: "City Watch 19", base_url: "https://city-watch19.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "city-watch19" },
  // { id: "timezone17", name: "Timezone 17", base_url: "https://timezone17.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "timezone17" },
  // { id: "watchflex_cartpe", name: "Watch Flex", base_url: "https://watchflex.cartpe.in/", category: "watches", method: "METHOD_A", searchKey: "watchflex" },

  // New jdwebconnect Watch Sites
  { id: "ticktock_connect", name: "ticktock", base_url: "https://ticktock.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "ticktock" },
  { id: "zenwatches", name: "zenwatches", base_url: "https://zenwatches.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "zenwatches" },
  { id: "timezone17_connect", name: "timezone17", base_url: "https://timezone17.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "timezone17" },
  { id: "kdenterprise_connect", name: "kdenterprise", base_url: "https://kdenterprise.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "kdenterprise" },
  { id: "watchflex_connect", name: "watchflex", base_url: "https://watchflex.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchflex" },
  { id: "watchfreak", name: "watchfreak", base_url: "https://watchfreak.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchfreak" },
  { id: "fashionpro123_connect", name: "fashionpro123", base_url: "https://fashionpro123.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "fashionpro123" },
  { id: "watchgallery", name: "watchgallery", base_url: "https://watchgallery.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchgallery" },
  { id: "watchwalain", name: "watchwalain", base_url: "https://watchwalain.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchwalain" },
  { id: "bismiwatch", name: "bismiwatch", base_url: "https://bismiwatch.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "bismiwatch" },
  { id: "metrowatches", name: "metrowatches", base_url: "https://metrowatches.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "metrowatches" },
  { id: "watchstreet_connect", name: "watch-street", base_url: "https://watch-street.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchstreet" },
  { id: "timepiece_connect", name: "timepiece", base_url: "https://timepiece.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "timepiece" },
  { id: "watchstudio12", name: "watchstudio12", base_url: "https://watchstudio12.jdwebnship.com", category: "watches", method: "METHOD_B", searchKey: "watchstudio12" },
  { id: "watchmart66", name: "watchmart66", base_url: "https://watchmart66.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "watchmart66" },
  { id: "timetraders", name: "timetraders", base_url: "https://timetraders.jdwebconnect.com/", category: "watches", method: "METHOD_B", searchKey: "timetraders" },

  // ================= SHOES SITES =================
  { id: "classyshoesreseller", name: "Classy Shoes Reseller", base_url: "https://classyshoesreseller.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "classyshoesreseller" },
  { id: "shoemartt", name: "Shoe Martt", base_url: "https://shoemartt.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoemartt" },
  { id: "fam-shoes", name: "Fam Shoes", base_url: "https://fam-shoes.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "fam-shoes" },
  { id: "reseller-orders", name: "Reseller Orders", base_url: "https://reseller-orders.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "reseller-orders" },
  { id: "resellerzone", name: "Reseller Zone", base_url: "https://resellerzone.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "resellerzone" },
  { id: "metro-kicks", name: "Metro Kicks", base_url: "https://metro-kicks.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "metro-kicks" },
  { id: "styleloop11", name: "Style Loop 11", base_url: "https://styleloop11.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "styleloop11" },
  { id: "spshoes", name: "SP Shoes", base_url: "https://spshoes.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "spshoes" },
  { id: "trademarkstore", name: "Trademark Store", base_url: "https://trademarkstore.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "trademarkstore" },
  { id: "greenenterprise", name: "Green Enterprise", base_url: "https://greenenterprise.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "greenenterprise" },
  { id: "4foxindia", name: "4 Fox India", base_url: "https://4foxindia.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "4foxindia" },
  { id: "hmsales", name: "HM Sales", base_url: "https://hmsales.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "hmsales" },
  { id: "shoegallery66", name: "Shoe Gallery 66", base_url: "https://shoegallery66.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoegallery66" },
  { id: "thecomfortzone", name: "The Comfort Zone", base_url: "https://thecomfortzone.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "thecomfortzone" },
  { id: "hotkickss", name: "Hot Kickss", base_url: "https://hotkickss.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "hotkickss" },
  { id: "laceupshoe", name: "Lace Up Shoe", base_url: "https://laceupshoe.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "laceupshoe" },
  { id: "shoezerry1", name: "Shoezerry 1", base_url: "https://shoezerry1.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoezerry1" },
  { id: "foot-shoppers", name: "Foot Shoppers", base_url: "https://foot-shoppers.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "foot-shoppers" },
  { id: "sneaker-zone", name: "Sneaker Zone", base_url: "https://sneaker-zone.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "sneaker-zone" },
  { id: "kamalenterprise", name: "Kamal Enterprise", base_url: "https://kamalenterprise.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "kamalenterprise" },
  { id: "bootsstudio", name: "Boots Studio", base_url: "https://bootsstudio.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "bootsstudio" },
  { id: "opalitess", name: "Opalitess", base_url: "https://opalitess.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "opalitess" },
  { id: "le-brouges-resell", name: "Le Brouges Resell", base_url: "https://le-brouges-resell.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "le-brouges-resell" },
  { id: "myorders", name: "My Orders", base_url: "https://myorders.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "myorders" },
  { id: "bismi-shoes", name: "Bismi Shoes", base_url: "https://bismi-shoes.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "bismi-shoes" },
  { id: "hubsneaker", name: "Hub Sneaker", base_url: "https://hubsneaker.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "hubsneaker" },
  { id: "oneshoess", name: "One Shoess", base_url: "https://oneshoess.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "oneshoess" },
  { id: "skicks2023", name: "SKicks 2023", base_url: "https://skicks2023.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "skicks2023" },
  { id: "thefashiontrendzmarketing", name: "The Fashion Trendz Marketing", base_url: "https://thefashiontrendzmarketing.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "thefashiontrendzmarketing" },
  { id: "mh-sneaker", name: "MH Sneaker", base_url: "https://mh-sneaker.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "mh-sneaker" },
  { id: "arsneakers", name: "AR Sneakers", base_url: "https://arsneakers.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "arsneakers" },
  { id: "supreme", name: "Supreme", base_url: "https://supreme.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "supreme" },
  { id: "dmienterprisee", name: "DMI Enterprisee", base_url: "https://dmienterprisee.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "dmienterprisee" },
  { id: "mangoenterprise11", name: "Mango Enterprise 11", base_url: "https://mangoenterprise11.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "mangoenterprise11" },
  { id: "classyslide", name: "Classy Slide", base_url: "https://classyslide.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "classyslide" },
  { id: "ffhouse", name: "FF House", base_url: "https://ffhouse.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "ffhouse" },
  { id: "reseller-store", name: "Reseller Store", base_url: "https://reseller-store.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "reseller-store" },
  { id: "boot-gallery", name: "Boot Gallery", base_url: "https://boot-gallery.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "boot-gallery" },
  { id: "dropshipresellers", name: "Dropship Resellers", base_url: "https://dropshipresellers.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "dropshipresellers" },
  { id: "ultimate-kicks", name: "Ultimate Kicks", base_url: "https://ultimate-kicks.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "ultimate-kicks" },
  { id: "signature-loafers-1", name: "Signature Loafers 1", base_url: "https://signature-loafers-1.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "signature-loafers-1" },
  { id: "shoefly1", name: "Shoe Fly 1", base_url: "https://shoefly1.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoefly1" },
  { id: "hypeshoe", name: "Hype Shoe", base_url: "https://hypeshoe.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "hypeshoe" },
  { id: "kicksmania777", name: "Kicks Mania 777", base_url: "https://kicksmania777.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "kicksmania777" },
  { id: "shoe-house-1", name: "Shoe House 1", base_url: "https://shoe-house-1.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoe-house-1" },
  { id: "shoebox-1", name: "Shoe Box 1", base_url: "https://shoebox-1.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoebox-1" },
  { id: "luxurystoreresell", name: "Luxury Store Resell", base_url: "https://luxurystoreresell.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "luxurystoreresell" },
  { id: "shoetrendzreseller", name: "Shoe Trendz Reseller", base_url: "https://shoetrendzreseller.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "shoetrendzreseller" },
  { id: "foot77loocker12", name: "Foot 77 Loocker 12", base_url: "https://foot77loocker12.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "foot77loocker12" },
  { id: "sneakerhunt", name: "sneakerhunt", base_url: "https://sneakerhunt.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "sneakerhunt" },
  { id: "royalshoes11", name: "royalshoes11", base_url: "https://royalshoes11.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "royalshoes11" },
  { id: "kickzhub", name: "kickzhub", base_url: "https://kickz-hub.cartpe.in/", category: "shoes", method: "METHOD_A", searchKey: "kickzhub" },
  { id: "shoeplanet", name: "shoeplanet", base_url: "https://shoeplanet.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "shoeplanet" },
  { id: "benzershoes", name: "benzershoes", base_url: "https://benzershoes.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "benzershoes" },
  { id: "shoezone17", name: "shoezone17", base_url: "https://shoezone17.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "shoezone17" },
  { id: "firekicks", name: "firekicks", base_url: "https://firekicks.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "firekicks" },
  { id: "thecomfortzone_jd", name: "thecomfortzone", base_url: "https://thecomfortzone.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "thecomfortzone" },
  { id: "dmienterprises", name: "dmienterprises", base_url: "https://dmienterprises.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "dmienterprises" },
  { id: "swagsole", name: "swagsole", base_url: "https://swagsole.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "swagsole" },
  { id: "mhsneaker", name: "mhsneaker", base_url: "https://mhsneaker.jdwebnship.com/", category: "shoes", method: "METHOD_B", searchKey: "mhsneaker" },

  // New jdwebconnect Shoe Sites
  { id: "benzershoes_connect", name: "benzershoes", base_url: "https://benzershoes.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "benzershoes" },
  { id: "swagsole_connect", name: "swagsole", base_url: "https://swagsole.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "swagsole" },
  { id: "shoeplanet_connect", name: "shoeplanet", base_url: "https://shoeplanet.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "shoeplanet" },
  { id: "shoezone17_connect", name: "shoezone17", base_url: "https://shoezone17.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "shoezone17" },
  { id: "flexsole", name: "flexsole", base_url: "https://flexsole.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "flexsole" },
  { id: "boot_gallery_connect", name: "boot-gallery", base_url: "https://boot-gallery.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "boot-gallery" },
  { id: "firekicks_connect", name: "firekicks", base_url: "https://firekicks.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "firekicks" },
  { id: "sneakerhunt_connect", name: "sneakerhunt", base_url: "https://sneakerhunt-a2vl.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "sneakerhunt" },
  { id: "thecomfortzone_connect", name: "thecomfortzone", base_url: "https://thecomfortzone.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "thecomfortzone" },
  { id: "mhsneaker_connect", name: "mhsneaker", base_url: "https://mhsneaker.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "mhsneaker" },
  { id: "dmienterprises_connect", name: "dmienterprises", base_url: "https://dmienterprises.jdwebconnect.com/", category: "shoes", method: "METHOD_B", searchKey: "dmienterprises" }
];